ALTER TABLE `artists` MODIFY COLUMN `createdAt` TIMESTAMP NOT NULL;
ALTER TABLE `artists` MODIFY COLUMN `updatedAt` TIMESTAMP NOT NULL;

ALTER TABLE `artworks` MODIFY COLUMN `createdAt` TIMESTAMP NOT NULL;
ALTER TABLE `artworks` MODIFY COLUMN `updatedAt` TIMESTAMP NOT NULL;

ALTER TABLE `ratings` MODIFY COLUMN `createdAt` TIMESTAMP NOT NULL;
ALTER TABLE `ratings` MODIFY COLUMN `updatedAt` TIMESTAMP NOT NULL;

ALTER TABLE `transactions` MODIFY COLUMN `createdAt` TIMESTAMP NOT NULL;
ALTER TABLE `transactions` MODIFY COLUMN `updatedAt` TIMESTAMP NOT NULL;

ALTER TABLE `users` MODIFY COLUMN `createdAt` TIMESTAMP NOT NULL;
ALTER TABLE `users` MODIFY COLUMN `updatedAt` TIMESTAMP NOT NULL;

ALTER TABLE `orders` MODIFY COLUMN `createdAt` TIMESTAMP NOT NULL;
ALTER TABLE `orders` MODIFY COLUMN `updatedAt` TIMESTAMP NOT NULL;

ALTER TABLE `ratings` MODIFY COLUMN `createdAt` TIMESTAMP NOT NULL;
ALTER TABLE `ratings` MODIFY COLUMN `updatedAt` TIMESTAMP NOT NULL;