INSERT INTO artists (name, email, password, bio) VALUES ("Picasso", "picasso@art.net", "123abc", "Born in Spain, was a child prodigy who was recognized as such by his art-teacher father, who ably led him along.");
INSERT INTO artists (name, email, password, bio) VALUES ("Michaelangelo", "stonegod@art.net", "rock0n", "Italian sculptor, painter, architect and poet. Michelangelo was one of the founders of the High Renaissance and, in his later years, one of the principal exponents of Mannerism.");
INSERT INTO artists (name, email, password, bio) VALUES ("Pollack", "splatterpaint@art.net", "Wh@t@M3spa55", "He was born in Cody, Wyoming, into a poor sheep farming family and was originally interested in sculpture, but joined the Art Students' League of New York in 1929 and was taught painting by Thomas Hart Benton.");
INSERT INTO artists (name, email, password, bio) VALUES ("Bob Ross", "hippypainter@art.net", "littleclouds", "American painter, art instructor, and television host. He was the creator and host of The Joy of Painting, an instructional television program that aired from 1983 to 1994 on PBS in the United States, and also aired in Canada, Latin America, and Europe.");
INSERT INTO artists (name, email, password, bio) VALUES ("Kodak", "cameraguy@art.net", "5@yCh3353", "American entrepreneur who founded the Eastman Kodak Company and popularized the use of roll film.");
INSERT INTO artists (name, email, password, bio) VALUES ("Salvador Dali", "mustache@dali.com", "andalucia", "Spanish painter. Born into a middle-class family, he studied at the Academy of Fine Arts in Madrid, where he mastered academic techniques.");
INSERT INTO artists (name, email, password, bio) VALUES ("Eva Hesse", "youngsculptor@stone.com", "r0ck0N", " Dying of brain cancer at thirty-four, an age at which most artist's careers are barely under way, she left a truncated body of work but one of remarkable power: an instrument of feeling that spoke of an inner life, sometimes fraught with anxiety.");
INSERT INTO artists (name, email, password, bio) VALUES ("Ansel Adams", "BWphotographer@gmail.com", "Na67de0", "American photographer and environmentalist.");
INSERT INTO artists (name, email, password, bio) VALUES ("Alphonse Mucha", "nouveauman@paris.com", "777ref3", "Graduate of the Academie Julian, whose first work was in the theatre and who never strayed far from it.");
INSERT INTO artists (name, email, password, bio) VALUES ("Ellen Schon", "potterygal@gmail.com", "1597534", "Ellen Schon has been exhibiting her works since the late 1970’s and currently lectures at the Art Institute of Boston.");


INSERT INTO artworks (title, category, description, media, rating, price, ArtistId) VALUES ("Girl with a Mandolin", "painting", "Created at the beginning of the cubist movement.  One of his most famous paintings.", "http://farm8.staticflickr.com/7719/17305794495_9aea9fd84e_z.jpg", 5, 10000000, 1);
INSERT INTO artworks (title, category, description, media, rating, price, ArtistId) VALUES ("Convergence", "painting", "A fine example of modern art through spatterpaint.",'http://www.konvero.com/wp-content/uploads/jackson-Pollock-Convergence.jpg', 5, 5000000, 3);
INSERT INTO artworks (title, category, description, media, rating, price, ArtistId) VALUES ("David", "sculpture", "The finest example of Italian renassaince sculpture known.", "http://caravaggista.com/wp-content/uploads/2011/09/michelangelo_david_head.jpg", 5, 40000000, 2);
INSERT INTO artworks (title, category, description, media, rating, price, ArtistId) VALUES ("Old Photograph", "photography", "An early photograph created with the new invention, the camera.", "http://cool.conservation-us.org/byorg/abbey/an/an26/an26-3/an26-3a.jpg", 3, 1000, 5);
INSERT INTO artworks (title, category, description, media, rating, price, ArtistId) VALUES ("Forest", "painting", "Painting created during Season 3, Episode 7 - Happy Trees in the Forest", "http://3.bp.blogspot.com/-YBG1JETlrPw/UI7qji67MnI/AAAAAAAAAqk/2LuwQfymC44/s1600/Bob-Ross.jpg", 3, 500, 4);
INSERT INTO artworks (title, category, description, media, rating, price, ArtistId) VALUES ("The Weeping Woman", "painting", "The Weeping Woman is an oil on canvas painted by Pablo Picasso in France in 1937.", "http://www.pablopicasso.org/images/paintings/the-weeping-woman.jpg", 4, 1000000, 1);
INSERT INTO artworks (title, category, description, media, rating, price, ArtistId) VALUES ("The Old Guitarist", "painting", "The Old Guitarist was painted in 1903, just after the suicide death of Picasso's close friend, Casagemas. During this time, the artist was sympathetic to the plight of the downtrodden and painted many canvases depicting the miseries of the poor, the ill, and those cast out of society.", "http://www.pablopicasso.org/images/paintings/the-old-guitarist.jpg", 5, 500000, 1);
INSERT INTO artworks (title, category, description, media, rating, price, ArtistId) VALUES ("Contingent", "sculpture", "Contingent is made of eight banner-like elements that hang from the ceiling. Each of these elements consists of a large rectangular stretch of latex-covered cheesecloth embedded at each end in a translucent field of fibreglass. The banners hang parallel to each other and at right angles to the wall.", "http://1.bp.blogspot.com/_b9nCuOI2P3M/TUIvDir4C0I/AAAAAAAAAMY/RomyXxYloG4/s1600/Eva-Hesse-Contingent.jpg", 3, 25000, 7);
INSERT INTO artworks (title, category, description, media, rating, price, ArtistId) VALUES ("Boulders in the Sierra Nevada", "photography", "Photograph from the east side of the Sierra Nevada Mountains, 1943.", "http://4.bp.blogspot.com/-GuDJghhL2Uc/TpfL8DLRbTI/AAAAAAAAAyk/cYHjlGBmLxk/s1600/ansel-adams-landscape-photography-mount-williamson-1944.jpg", 4, 2600, 8);
INSERT INTO artworks (title, category, description, media, rating, price, ArtistId) VALUES ("Mountain-scape","photography", "Spring strorm in the Grand Teton Mountains, Wyoming", "https://photogrist.com/wp-content/uploads/2014/05/Ansel-Adams6.jpg", 4, 1000, 8);
INSERT INTO artworks (title, category, description, media, rating, price, ArtistId) VALUES ("Soft Construction with Boiled Beans", "painting", "Dalí created this piece to represent the horrors of the Spanish Civil War.", "https://upload.wikimedia.org/wikipedia/en/8/89/SalvadorDali-SoftConstructionWithBeans.jpg", 5, 2500000, 6);
INSERT INTO artworks (title, category, description, media, rating, price, ArtistId) VALUES ("The Persistence of Memory", "painting", " It is widely recognized and frequently referenced in popular culture, and sometimes referred to by more descriptive (though incorrect) titles, such as 'The Soft Watches' or 'The Melting Watches'", "https://en.wikipedia.org/wiki/The_Persistence_of_Memory#/media/File:The_Persistence_of_Memory.jpg", 5, 100000, 6);
INSERT INTO artworks (title, category, description, media, rating, price, ArtistId) VALUES ("Cabaret Scene", "painting", " This was a unique cubist experiment that came between Dalí's early impressionist work and the classic surrealist technique he would later develop.", "https://en.wikipedia.org/wiki/Cabaret_Scene#/media/File:Cabaret_Scene.jpg", 4, 10000, 6);
INSERT INTO artworks (title, category, description, media, rating, price, ArtistId) VALUES ("Bottle Series", "sculpture", "This series explores the ceramic vessel as Bottle, evoking the gesture and anthropomorphized stance of the human body.", "http://ellenschon.com/bottle-series/1/0", 3, 500, 10);
INSERT INTO artworks (title, category, description, media, rating, price, ArtistId) VALUES ("Job Cigarettes", "painting", "One of Mucha’s best-known advertising posters, with numerous editions subsequently published in a variety of formats for international markets.", "https://en.wikipedia.org/wiki/Alphonse_Mucha#/media/File:Alphonse_Mucha_-_Job_Cigarettes_1.jpg", 4, 450, 9);
INSERT INTO artworks (title, category, description, media, rating, price, ArtistId) VALUES ("Zodiac", "painting", "Zodiac was Mucha's first work under his contract with the printer Champenois and was originally designed as an in-house calendar for the company.", "https://en.wikipedia.org/wiki/Alphonse_Mucha#/media/File:Alphonse_Mucha_-_Zodiac.jpg", 5, 500, 9);
INSERT INTO artworks (title, category, description, media, rating, price, ArtistId) VALUES ("Beautiful", "painting", "Beautiful mountains and trees around this log cabin.", "http://img.xcitefun.net/users/2009/03/41037xcitefun-bob-ross-paintings-beautiful-4.jpg", 3, 420, 4);
INSERT INTO artworks (title, category, description, media, rating, price, ArtistId) VALUES ("Planet #1", "ceramic", "Hand thrown ceramics inspired by the universe.", "http://ellenschon.com/colored-clay-/planet-series/1/8", 4, 300, 10);
INSERT INTO artworks (title, category, description, media, rating, price, ArtistId) VALUES ("Receding Mountains", "ceramic", "Tea bowls influenced by the world around us.", "http://ellenschon.com/colored-clay-/chawans/1/0", 3, 250, 10);


INSERT INTO users (name, email, password) VALUES ("Bob Smith", "bsmith@gmail.com", "123789");
INSERT INTO users (name, email, password) VALUES ("Mary Jones", "m_jones@yahoo.com", "444nnn");
INSERT INTO users (name, email, password) VALUES ("Dougie Doug", "bigDoug@gmail.com", "654qwert");
INSERT INTO users (name, email, password) VALUES ("Migos", "migos@migos.net", "M1g0srul3");
INSERT INTO users (name, email, password) VALUES ("Mrs. Doubtfire", "saucynanny@nanny.net", "1597546lwl");
